version: '3'

networks:
  whaticket:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - DB_NAME=${MYSQL_DATABASE:-whaticket}
      - DB_TIMEZONE=${DB_TIMEZONE:--03:00}
      - DB_DIALECT=${DB_DIALECT:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PROXY_PORT=${PROXY_PORT:-8080}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    ports:
      - ${BACKEND_PORT:-8080}:3000
    volumes:
      - ./backend/public/:/usr/src/app/public/
      - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
    depends_on:
      - mysql
    restart: always
    networks:
      - whaticket



  mysql:
    image: ${MYSQL_ENGINE:-mariadb}:${MYSQL_VERSION:-10.6}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin    
    volumes:
      - ./.docker/data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-whaticket}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - TZ=${TZ:-America/Fortaleza}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    restart: always
    networks:
      - whaticket